'use client';
import { useEffect,useState,type FormEvent } from 'react';
import Link from 'next/link';
import type { StaffUser } from '@/lib/types';
import { useStaff } from './staff-gate';
export default function EmployeeUsers(){
  const actor=useStaff();
  const [users,setUsers]=useState<StaffUser[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [credential,setCredential]=useState<{user:StaffUser;pin:string}|null>(null);
  async function refresh(){const response=await fetch('/api/users',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);setUsers(data);}
  useEffect(()=>{if(actor&&actor.role!=='attendant')void refresh().catch(e=>setError(e.message));},[actor?.id]);
  async function mutate(input:Record<string,unknown>){setBusy(true);setError('');setCredential(null);try{const response=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const result=await response.json();if(!response.ok)throw new Error(result.error);if(result.pin)setCredential(result);await refresh();return true;}catch(e){setError(e instanceof Error?e.message:'Unable to save employee.');return false;}finally{setBusy(false);}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));if(await mutate({...data,action:'create'}))form.reset();}
  if(!actor||actor.role==='attendant')return <main className="employee-users"><h1>Employee access restricted</h1><p>Ask a manager or administrator to manage employees.</p><Link href="/worker">Back to worker station</Link></main>;
  const roles=actor.role==='admin'?['attendant','manager','admin']:['attendant'];
  return <main className="employee-users"><Link href="/">← Valet operations</Link><h1>Employees & access</h1><p>{actor.role==='admin'?'Manage employee roles, access and PINs.':'Add attendants and manage their access and PINs.'}</p><section className="panel employee-user-create"><h2>Add employee</h2><form onSubmit={create}><div className="form-grid"><label className="field">Full name<input name="name" required maxLength={100} /></label><label className="field">Employee ID<input name="username" required pattern="[A-Za-z0-9][A-Za-z0-9._\-]{2,39}" minLength={3} maxLength={40} autoCapitalize="none" /></label><label className="field">Role<select name="role" defaultValue="attendant">{roles.map(role=><option key={role}>{role}</option>)}</select></label></div><button className="button primary" disabled={busy}>Create employee & generate PIN</button></form></section>{credential&&<section className="employee-pin" role="status"><strong>{credential.user.name} · {credential.user.username}</strong><p>New PIN: <code>{credential.pin}</code></p><p>Shown once. Share privately with this employee. Resetting a PIN signs out their existing sessions.</p><button type="button" className="button secondary" onClick={()=>setCredential(null)}>I've recorded it securely</button></section>}{error&&<p className="form-error" role="alert">{error}</p>}<section className="panel employee-user-list"><h2>Employee accounts</h2>{users.map(user=><form key={`${user.id}-${user.role}-${user.active}`} onSubmit={event=>{event.preventDefault();const role=new FormData(event.currentTarget).get('role');void mutate({action:'update',id:user.id,role,active:user.active});}}><div><strong>{user.name}</strong><p>{user.username} · {user.active?'Active':'Inactive'}</p></div><label className="field">Role<select name="role" defaultValue={user.role} disabled={busy||user.id===actor.id}>{roles.map(role=><option key={role}>{role}</option>)}</select></label><button className="button secondary" disabled={busy||user.id===actor.id}>Save role</button><button className="button secondary" type="button" disabled={busy} onClick={()=>void mutate({action:'reset-pin',id:user.id})}>Reset PIN</button><button className="button secondary" type="button" disabled={busy||user.id===actor.id} onClick={()=>void mutate({action:'update',id:user.id,role:user.role,active:!user.active})}>{user.active?'Deactivate':'Reactivate'}</button></form>)}</section></main>;
}
